# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20151205_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'Dude', 'Dude'), (b'Betty', 'Betty')], max_length=6),
        ),
    ]
