# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20151207_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='available_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
