# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20151229_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='times_flagged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
