# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_myuser_times_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='blocked_users',
            field=models.ManyToManyField(related_name='_myuser_blocked_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
