# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_myuser_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='blocked_users',
        ),
        migrations.AddField(
            model_name='myuser',
            name='blocking',
            field=models.ManyToManyField(related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
