# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20160113_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_status', models.IntegerField(choices=[(0, 'Pending review'), (1, 'In review'), (2, 'Approved'), (3, 'Declined'), (4, 'Black listed')], default=0)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('company_website', models.CharField(blank=True, max_length=90)),
                ('twitter', models.CharField(blank=True, max_length=80)),
                ('instagram', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=False)),
                ('creations_allowed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
