# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 11:49
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to=accounts.models.company_upload_location),
        ),
    ]
